export const AUTH_START_USER = 'AUTH_START_USER';
export const AUTH_SUCCESS_USER = 'AUTH_SUCCESS_USER';
export const AUTH_FAIL_USER = 'AUTH_FAIL_USER';
export const AUTH_USER_USER = 'AUTH_USER_USER';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
