//Register
export const AUTH_START_USER_REGISTER_OTP = 'AUTH_START_USER_REGISTER_OTP';
export const AUTH_START_USER_REGISTER_OTP_SUCCESS = 'AUTH_START_USER_REGISTER_OTP_SUCCESS';
export const AUTH_USER_REGISTER_OTP_FAIL_OTP = 'AUTH_USER_REGISTER_OTP_FAIL_OTP';
export const Auth_USER_OTP_SUCCESS = 'Auth_USER_OTP_SUCCESS';

export const AUTH_START_USER = 'AUTH_START_USER_REGISTER';
export const AUTH_SUCCESS_USER = 'AUTH_SUCCESS_USER';
export const AUTH_FAIL_USER = 'AUTH_FAIL_USER';
export const AUTH_USER_USER = 'AUTH_USER_USER';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';

//REGISTER USER

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_OTP_SEND = 'REGISTER_USER_OTP_SEND';
export const REGISTER_USER_OTP_FAIL = 'REGISTER_USER_OTP_FAIL';
